config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "posts#index"

  get 'about' => 'pages#about'

  resources :posts do 
    resources :comments
  end 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  #dependent makes it so that when you destroy a post the comments go as well.
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end 

  def destroy
    #After I did this I went to the _comment.html.erb file see B on that file. 
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index 
    @posts = Post.all.order('created_at DESC')
  end 

  def new 
    @post = Post.new
  end 

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end 
  end 

  def show 
    @post = Post.find(params[:id])
  end 

  def edit 
    @post = Post.find(params[:id])
  end 

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else 
      render 'edit'
    end 
  end 

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end 

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>

  <!-- The below was added to delete -->
  <% if user_signed_in? %>
    <p>
      <%= link_to "Delete", [comment.post, comment], method: :delete, class: "button", data: {
        confirm: "Are you sure?" } %>
    </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cuddlr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <ul>
      <li class="category"><%= link_to "Cuddlr", root_path %></li>
      <li><%= link_to "Posts", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
    <% if !user_signed_in? %>
      <p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
    <% end %>
  </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>Post Feed</p>
      <% elsif current_page?(about_path) %>
        <p>My Site</p>
      <% else %>
        <%= link_to "Back to Post Feed", root_path %>
      <% end %>
      
      <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "Make Post", new_post_path %></button>
          <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
        </div>
      <% end %>

    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpeg" %>
  </div>

  <div id="content">
    <h1>Me</h1>
    <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
  </div>

</div>

app/views/posts/_form.html.erb
  <!-- Creating the form to enter in data -->
  <%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  
  <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Fix Post</h1>
    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="body"><%= truncate(post.body, length: 200) %></p>
    <p class="date">About <%= time_ago_in_words(post.created_at) %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Make Something</h1>

  <!-- Creating the form to enter in data -->
  <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> stopped this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  
  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago 
    <% if user_signed_in? %>
      <%= link_to "Edit", edit_post_path(@post) %> |
      <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3> Join Discussion </h3>
    <%= render "comments/form" %>
  </div>
</div>